In [1]:
import pandas as pd

In [6]:
df = pd.DataFrame({
    "country" : ["USA","USA" , "India", "India"],
    "year" : [2020 , 2021, 2020, 2021],
    "sales" : [100,120,90,110],
    "profit" : [20,25,18,22],

}) 
df

  country  year  sales  profit  tax
0     USA  2020    100      20   10
1     USA  2021    120      25   20
2   India  2020     90      18   30
3   India  2021    110      22   40

In [8]:
# melt function - wide to long format
melted_df = df.melt(
    id_vars = ["country" , "year"] , #these columns will not change and will be preserved
    value_vars = ["sales","profit"] , #these are the values that we are changing here we r combing it into one column
    var_name = "metrics" , 
    value_name = "value"    
)

In [12]:
# Pivot function - Long to wide format

original = melted_df.pivot(
    index = ["country","year"],
    columns = "metrics",
    values = "value"
)
original

metrics       profit  sales
country year
India   2020      18     90
        2021      22    110
USA     2020      20    100
        2021      25    120

In [13]:
df

  country  year  sales  profit  tax
0     USA  2020    100      20   10
1     USA  2021    120      25   20
2   India  2020     90      18   30
3   India  2021    110      22   40